DELETE FROM country;
DELETE FROM region;

INSERT INTO region VALUES (1, "Europe");
INSERT INTO region VALUES (2, "Asia");
INSERT INTO region VALUES (3, "Americas");
INSERT INTO region VALUES (4, "Africa");
INSERT INTO region VALUES (5, "Oceania");
INSERT INTO region VALUES (6, "Other");

INSERT INTO country VALUES ("Afghanistan", 004, "AF", 2, NULL);
INSERT INTO country VALUES ("Åland Islands", 248, "AX", 1, NULL);
INSERT INTO country VALUES ("Albania", 008, "AL", 1, NULL);
INSERT INTO country VALUES ("Algeria", 012, "DZ", 4, NULL);
INSERT INTO country VALUES ("American Samoa", 016, "AS", 5, NULL);
INSERT INTO country VALUES ("Andorra", 020, "AD", 1, NULL);
INSERT INTO country VALUES ("Angola", 024, "AO", 4, NULL);
INSERT INTO country VALUES ("Anguilla", 660, "AI", 3, NULL);
INSERT INTO country VALUES ("Antarctica", 010, "AQ", 6, NULL);
INSERT INTO country VALUES ("Antigua and Barbuda", 028, "AG", 3, NULL);
INSERT INTO country VALUES ("Argentina", 032, "AR", 3, NULL);
INSERT INTO country VALUES ("Armenia", 051, "AM", 2, NULL);
INSERT INTO country VALUES ("Aruba", 533, "AW", 3, NULL);
INSERT INTO country VALUES ("Australia", 036, "AU", 5, NULL);
INSERT INTO country VALUES ("Austria", 040, "AT", 1, NULL);
INSERT INTO country VALUES ("Azerbaijan", 031, "AZ", 2, NULL);
INSERT INTO country VALUES ("Bahamas", 044, "BS", 3, NULL);
INSERT INTO country VALUES ("Bahrain", 048, "BH", 2, NULL);
INSERT INTO country VALUES ("Bangladesh", 050, "BD", 2, NULL);
INSERT INTO country VALUES ("Barbados", 052, "BB", 3, NULL);
INSERT INTO country VALUES ("Belarus", 112, "BY", 1, NULL);
INSERT INTO country VALUES ("Belgium", 056, "BE", 1, NULL);
INSERT INTO country VALUES ("Belize", 084, "BZ", 3, NULL);
INSERT INTO country VALUES ("Benin", 204, "BJ", 4, NULL);
INSERT INTO country VALUES ("Bermuda", 060, "BM", 3, NULL);
INSERT INTO country VALUES ("Bhutan", 064, "BT", 2, NULL);
INSERT INTO country VALUES ("Bolivia", 068, "BO", 3, NULL);
INSERT INTO country VALUES ("Bonaire, Sint Eustatius and Saba", 535, "BQ", 3, NULL);
INSERT INTO country VALUES ("Bosnia and Herzegovina", 070, "BA", 1, NULL);
INSERT INTO country VALUES ("Botswana", 072, "BW", 4, NULL);
INSERT INTO country VALUES ("Bouvet Island", 074, "BV", 3, NULL);
INSERT INTO country VALUES ("Brazil", 076, "BR", 3, NULL);
INSERT INTO country VALUES ("British Indian Ocean Territory", 086, "IO", 4, NULL);
INSERT INTO country VALUES ("Brunei", 096, "BN", 2, NULL);
INSERT INTO country VALUES ("Bulgaria", 100, "BG", 1, NULL);
INSERT INTO country VALUES ("Burkina Faso", 854, "BF", 4, NULL);
INSERT INTO country VALUES ("Burundi", 108, "BI", 4, NULL);
INSERT INTO country VALUES ("Cabo Verde", 132, "CV", 4, NULL);
INSERT INTO country VALUES ("Cambodia", 116, "KH", 2, NULL);
INSERT INTO country VALUES ("Cameroon", 120, "CM", 4, NULL);
INSERT INTO country VALUES ("Canada", 124, "CA", 3, NULL);
INSERT INTO country VALUES ("Cayman Islands", 136, "KY", 3, NULL);
INSERT INTO country VALUES ("Central African Republic", 140, "CF", 4, NULL);
INSERT INTO country VALUES ("Chad", 148, "TD", 4, NULL);
INSERT INTO country VALUES ("Chile", 152, "CL", 3, NULL);
INSERT INTO country VALUES ("China", 156, "CN", 2, NULL);
INSERT INTO country VALUES ("Christmas Island", 162, "CX", 5, NULL);
INSERT INTO country VALUES ("Cocos (Keeling) Islands", 166, "CC", 5, NULL);
INSERT INTO country VALUES ("Colombia", 170, "CO", 3, NULL);
INSERT INTO country VALUES ("Comoros", 174, "KM", 4, NULL);
INSERT INTO country VALUES ("Congo (Brazzaville)", 178, "CG", 4, NULL);
INSERT INTO country VALUES ("Congo (Kinshasa)", 180, "CD", 4, NULL);
INSERT INTO country VALUES ("Cook Islands", 184, "CK", 5, NULL);
INSERT INTO country VALUES ("Costa Rica", 188, "CR", 3, NULL);
INSERT INTO country VALUES ("Cote d'Ivoire", 384, "CI", 4, NULL);
INSERT INTO country VALUES ("Croatia", 191, "HR", 1, NULL);
INSERT INTO country VALUES ("Cuba", 192, "CU", 3, NULL);
INSERT INTO country VALUES ("Curaçao", 531, "CW", 3, NULL);
INSERT INTO country VALUES ("Cyprus", 196, "CY", 2, NULL);
INSERT INTO country VALUES ("Czechia", 203, "CZ", 1, NULL);
INSERT INTO country VALUES ("Denmark", 208, "DK", 1, NULL);
INSERT INTO country VALUES ("Djibouti", 262, "DJ", 4, NULL);
INSERT INTO country VALUES ("Dominica", 212, "DM", 3, NULL);
INSERT INTO country VALUES ("Dominican Republic", 214, "DO", 3, NULL);
INSERT INTO country VALUES ("Ecuador", 218, "EC", 3, NULL);
INSERT INTO country VALUES ("Egypt", 818, "EG", 4, NULL);
INSERT INTO country VALUES ("El Salvador", 222, "SV", 3, NULL);
INSERT INTO country VALUES ("Equatorial Guinea", 226, "GQ", 4, NULL);
INSERT INTO country VALUES ("Eritrea", 232, "ER", 4, NULL);
INSERT INTO country VALUES ("Estonia", 233, "EE", 1, NULL);
INSERT INTO country VALUES ("Eswatini", 748, "SZ", 4, NULL);
INSERT INTO country VALUES ("Ethiopia", 231, "ET", 4, NULL);
INSERT INTO country VALUES ("Falkland Islands (Malvinas)", 238, "FK", 3, NULL);
INSERT INTO country VALUES ("Faroe Islands", 234, "FO", 1, NULL);
INSERT INTO country VALUES ("Fiji", 242, "FJ", 5, NULL);
INSERT INTO country VALUES ("Finland", 246, "FI", 1, NULL);
INSERT INTO country VALUES ("France", 250, "FR", 1, NULL);
INSERT INTO country VALUES ("French Guiana", 254, "GF", 3, NULL);
INSERT INTO country VALUES ("French Polynesia", 258, "PF", 5, NULL);
INSERT INTO country VALUES ("French Southern Territories", 260, "TF", 4, NULL);
INSERT INTO country VALUES ("Gabon", 266, "GA", 4, NULL);
INSERT INTO country VALUES ("Gambia", 270, "GM", 4, NULL);
INSERT INTO country VALUES ("Georgia", 268, "GE", 2, NULL);
INSERT INTO country VALUES ("Germany", 276, "DE", 1, NULL);
INSERT INTO country VALUES ("Ghana", 288, "GH", 4, NULL);
INSERT INTO country VALUES ("Gibraltar", 292, "GI", 1, NULL);
INSERT INTO country VALUES ("Greece", 300, "GR", 1, NULL);
INSERT INTO country VALUES ("Greenland", 304, "GL", 3, NULL);
INSERT INTO country VALUES ("Grenada", 308, "GD", 3, NULL);
INSERT INTO country VALUES ("Guadeloupe", 312, "GP", 3, NULL);
INSERT INTO country VALUES ("Guam", 316, "GU", 5, NULL);
INSERT INTO country VALUES ("Guatemala", 320, "GT", 3, NULL);
INSERT INTO country VALUES ("Guernsey", 831, "GG", 1, NULL);
INSERT INTO country VALUES ("Guinea", 324, "GN", 4, NULL);
INSERT INTO country VALUES ("Guinea-Bissau", 624, "GW", 4, NULL);
INSERT INTO country VALUES ("Guyana", 328, "GY", 3, NULL);
INSERT INTO country VALUES ("Haiti", 332, "HT", 3, NULL);
INSERT INTO country VALUES ("Heard Island and McDonald Islands", 334, "HM", 5, NULL);
INSERT INTO country VALUES ("Holy See", 336, "VA", 1, NULL);
INSERT INTO country VALUES ("Honduras", 340, "HN", 3, NULL);
INSERT INTO country VALUES ("Hong Kong", 344, "HK", 2, NULL);
INSERT INTO country VALUES ("Hungary", 348, "HU", 1, NULL);
INSERT INTO country VALUES ("Iceland", 352, "IS", 1, NULL);
INSERT INTO country VALUES ("India", 356, "IN", 2, NULL);
INSERT INTO country VALUES ("Indonesia", 360, "ID", 2, NULL);
INSERT INTO country VALUES ("Iran", 364, "IR", 2, NULL);
INSERT INTO country VALUES ("Iraq", 368, "IQ", 2, NULL);
INSERT INTO country VALUES ("Ireland", 372, "IE", 1, NULL);
INSERT INTO country VALUES ("Isle of Man", 833, "IM", 1, NULL);
INSERT INTO country VALUES ("Israel", 376, "IL", 2, NULL);
INSERT INTO country VALUES ("Italy", 380, "IT", 1, NULL);
INSERT INTO country VALUES ("Jamaica", 388, "JM", 3, NULL);
INSERT INTO country VALUES ("Japan", 392, "JP", 2, NULL);
INSERT INTO country VALUES ("Jersey", 832, "JE", 1, NULL);
INSERT INTO country VALUES ("Jordan", 400, "JO", 2, NULL);
INSERT INTO country VALUES ("Kazakhstan", 398, "KZ", 2, NULL);
INSERT INTO country VALUES ("Kenya", 404, "KE", 4, NULL);
INSERT INTO country VALUES ("Kiribati", 296, "KI", 5, NULL);
INSERT INTO country VALUES ("Korea, South", 408, "KR", 2, NULL);
INSERT INTO country VALUES ("Korea, Republic of", 410, "KP", 2, NULL);
INSERT INTO country VALUES ("Kuwait", 414, "KW", 2, NULL);
INSERT INTO country VALUES ("Kyrgyzstan", 417, "KG", 2, NULL);
INSERT INTO country VALUES ("Laos", 418, "LA", 2, NULL);
INSERT INTO country VALUES ("Latvia", 428, "LV", 1, NULL);
INSERT INTO country VALUES ("Lebanon", 422, "LB", 2, NULL);
INSERT INTO country VALUES ("Lesotho", 426, "LS", 4, NULL);
INSERT INTO country VALUES ("Liberia", 430, "LR", 4, NULL);
INSERT INTO country VALUES ("Libya", 434, "LY", 4, NULL);
INSERT INTO country VALUES ("Liechtenstein", 438, "LI", 1, NULL);
INSERT INTO country VALUES ("Lithuania", 440, "LT", 1, NULL);
INSERT INTO country VALUES ("Luxembourg", 442, "LU", 1, NULL);
INSERT INTO country VALUES ("Macao", 446, "MO", 2, NULL);
INSERT INTO country VALUES ("Madagascar", 450, "MG", 4, NULL);
INSERT INTO country VALUES ("Malawi", 454, "MW", 4, NULL);
INSERT INTO country VALUES ("Malaysia", 458, "MY", 2, NULL);
INSERT INTO country VALUES ("Maldives", 462, "MV", 2, NULL);
INSERT INTO country VALUES ("Mali", 466, "ML", 4, NULL);
INSERT INTO country VALUES ("Malta", 470, "MT", 1, NULL);
INSERT INTO country VALUES ("Marshall Islands", 584, "MH", 5, NULL);
INSERT INTO country VALUES ("Martinique", 474, "MQ", 3, NULL);
INSERT INTO country VALUES ("Mauritania", 478, "MR", 4, NULL);
INSERT INTO country VALUES ("Mauritius", 480, "MU", 4, NULL);
INSERT INTO country VALUES ("Mayotte", 175, "YT", 4, NULL);
INSERT INTO country VALUES ("Mexico", 484, "MX", 3, NULL);
INSERT INTO country VALUES ("Micronesia (Federated States of)", 583, "FM", 5, NULL);
INSERT INTO country VALUES ("Moldova", 498, "MD", 1, NULL);
INSERT INTO country VALUES ("Monaco", 492, "MC", 1, NULL);
INSERT INTO country VALUES ("Mongolia", 496, "MN", 2, NULL);
INSERT INTO country VALUES ("Montenegro", 499, "ME", 1, NULL);
INSERT INTO country VALUES ("Montserrat", 500, "MS", 3, NULL);
INSERT INTO country VALUES ("Morocco", 504, "MA", 4, NULL);
INSERT INTO country VALUES ("Mozambique", 508, "MZ", 4, NULL);
INSERT INTO country VALUES ("Burma", 104, "MM", 2, NULL);
INSERT INTO country VALUES ("Namibia", 516, "NA", 4, NULL);
INSERT INTO country VALUES ("Nauru", 520, "NR", 5, NULL);
INSERT INTO country VALUES ("Nepal", 524, "NP", 2, NULL);
INSERT INTO country VALUES ("Netherlands", 528, "NL", 1, NULL);
INSERT INTO country VALUES ("New Caledonia", 540, "NC", 5, NULL);
INSERT INTO country VALUES ("New Zealand", 554, "NZ", 5, NULL);
INSERT INTO country VALUES ("Nicaragua", 558, "NI", 3, NULL);
INSERT INTO country VALUES ("Niger", 562, "NE", 4, NULL);
INSERT INTO country VALUES ("Nigeria", 566, "NG", 4, NULL);
INSERT INTO country VALUES ("Niue", 570, "NU", 5, NULL);
INSERT INTO country VALUES ("Norfolk Island", 574, "NF", 5, NULL);
INSERT INTO country VALUES ("North Macedonia", 807, "MK", 1, NULL);
INSERT INTO country VALUES ("Northern Mariana Islands", 580, "MP", 5, NULL);
INSERT INTO country VALUES ("Norway", 578, "NO", 1, NULL);
INSERT INTO country VALUES ("Oman", 512, "OM", 2, NULL);
INSERT INTO country VALUES ("Pakistan", 586, "PK", 2, NULL);
INSERT INTO country VALUES ("Palau", 585, "PW", 5, NULL);
INSERT INTO country VALUES ("Palestine, State of", 275, "PS", 2, NULL);
INSERT INTO country VALUES ("Panama", 591, "PA", 3, NULL);
INSERT INTO country VALUES ("Papua New Guinea", 598, "PG", 5, NULL);
INSERT INTO country VALUES ("Paraguay", 600, "PY", 3, NULL);
INSERT INTO country VALUES ("Peru", 604, "PE", 3, NULL);
INSERT INTO country VALUES ("Philippines", 608, "PH", 2, NULL);
INSERT INTO country VALUES ("Pitcairn", 612, "PN", 5, NULL);
INSERT INTO country VALUES ("Poland", 616, "PL", 1, NULL);
INSERT INTO country VALUES ("Portugal", 620, "PT", 1, NULL);
INSERT INTO country VALUES ("Puerto Rico", 630, "PR", 3, NULL);
INSERT INTO country VALUES ("Qatar", 634, "QA", 2, NULL);
INSERT INTO country VALUES ("Réunion", 638, "RE", 4, NULL);
INSERT INTO country VALUES ("Romania", 642, "RO", 1, NULL);
INSERT INTO country VALUES ("Russia", 643, "RU", 1, NULL);
INSERT INTO country VALUES ("Rwanda", 646, "RW", 4, NULL);
INSERT INTO country VALUES ("Saint Barthélemy", 652, "BL", 3, NULL);
INSERT INTO country VALUES ("Saint Helena, Ascension and Tristan da Cunha", 654, "SH", 4, NULL);
INSERT INTO country VALUES ("Saint Kitts and Nevis", 659, "KN", 3, NULL);
INSERT INTO country VALUES ("Saint Lucia", 662, "LC", 3, NULL);
INSERT INTO country VALUES ("Saint Martin (French part)", 663, "MF", 3, NULL);
INSERT INTO country VALUES ("Saint Pierre and Miquelon", 666, "PM", 3, NULL);
INSERT INTO country VALUES ("Saint Vincent and the Grenadines", 670, "VC", 3, NULL);
INSERT INTO country VALUES ("Samoa", 882, "WS", 5, NULL);
INSERT INTO country VALUES ("San Marino", 674, "SM", 1, NULL);
INSERT INTO country VALUES ("Sao Tome and Principe", 678, "ST", 4, NULL);
INSERT INTO country VALUES ("Saudi Arabia", 682, "SA", 2, NULL);
INSERT INTO country VALUES ("Senegal", 686, "SN", 4, NULL);
INSERT INTO country VALUES ("Serbia", 688, "RS", 1, NULL);
INSERT INTO country VALUES ("Seychelles", 690, "SC", 4, NULL);
INSERT INTO country VALUES ("Sierra Leone", 694, "SL", 4, NULL);
INSERT INTO country VALUES ("Singapore", 702, "SG", 2, NULL);
INSERT INTO country VALUES ("Sint Maarten (Dutch part)", 534, "SX", 3, NULL);
INSERT INTO country VALUES ("Slovakia", 703, "SK", 1, NULL);
INSERT INTO country VALUES ("Slovenia", 705, "SI", 1, NULL);
INSERT INTO country VALUES ("Solomon Islands", 090, "SB", 5, NULL);
INSERT INTO country VALUES ("Somalia", 706, "SO", 4, NULL);
INSERT INTO country VALUES ("South Africa", 710, "ZA", 4, NULL);
INSERT INTO country VALUES ("South Georgia and the South Sandwich Islands", 239, "GS", 3, NULL);
INSERT INTO country VALUES ("South Sudan", 728, "SS", 4, NULL);
INSERT INTO country VALUES ("Spain", 724, "ES", 1, NULL);
INSERT INTO country VALUES ("Sri Lanka", 144, "LK", 2, NULL);
INSERT INTO country VALUES ("Sudan", 729, "SD", 4, NULL);
INSERT INTO country VALUES ("Suriname", 740, "SR", 3, NULL);
INSERT INTO country VALUES ("Svalbard and Jan Mayen", 744, "SJ", 1, NULL);
INSERT INTO country VALUES ("Sweden", 752, "SE", 1, NULL);
INSERT INTO country VALUES ("Switzerland", 756, "CH", 1, NULL);
INSERT INTO country VALUES ("Syria", 760, "SY", 2, NULL);
INSERT INTO country VALUES ("Taiwan*", 158, "TW", 2, NULL);
INSERT INTO country VALUES ("Tajikistan", 762, "TJ", 2, NULL);
INSERT INTO country VALUES ("Tanzania", 834, "TZ", 4, NULL);
INSERT INTO country VALUES ("Thailand", 764, "TH", 2, NULL);
INSERT INTO country VALUES ("Timor-Leste", 626, "TL", 2, NULL);
INSERT INTO country VALUES ("Togo", 768, "TG", 4, NULL);
INSERT INTO country VALUES ("Tokelau", 772, "TK", 5, NULL);
INSERT INTO country VALUES ("Tonga", 776, "TO", 5, NULL);
INSERT INTO country VALUES ("Trinidad and Tobago", 780, "TT", 3, NULL);
INSERT INTO country VALUES ("Tunisia", 788, "TN", 4, NULL);
INSERT INTO country VALUES ("Turkey", 792, "TR", 2, NULL);
INSERT INTO country VALUES ("Turkmenistan", 795, "TM", 2, NULL);
INSERT INTO country VALUES ("Turks and Caicos Islands", 796, "TC", 3, NULL);
INSERT INTO country VALUES ("Tuvalu", 798, "TV", 5, NULL);
INSERT INTO country VALUES ("Uganda", 800, "UG", 4, NULL);
INSERT INTO country VALUES ("Ukraine", 804, "UA", 1, NULL);
INSERT INTO country VALUES ("United Arab Emirates", 784, "AE", 2, NULL);
INSERT INTO country VALUES ("United Kingdom", 826, "GB", 1, NULL);
INSERT INTO country VALUES ("US", 840, "US", 3, NULL);
INSERT INTO country VALUES ("United States Minor Outlying Islands", 581, "UM", 5, NULL);
INSERT INTO country VALUES ("Uruguay", 858, "UY", 3, NULL);
INSERT INTO country VALUES ("Uzbekistan", 860, "UZ", 2, NULL);
INSERT INTO country VALUES ("Vanuatu", 548, "VU", 5, NULL);
INSERT INTO country VALUES ("Venezuela", 862, "VE", 3, NULL);
INSERT INTO country VALUES ("Vietnam", 704, "VN", 2, NULL);
INSERT INTO country VALUES ("Virgin Islands (British)", 092, "VG", 3, NULL);
INSERT INTO country VALUES ("Virgin Islands (U.S.)", 850, "VI", 3, NULL);
INSERT INTO country VALUES ("Wallis and Futuna", 876, "WF", 5, NULL);
INSERT INTO country VALUES ("Western Sahara", 732, "EH", 4, NULL);
INSERT INTO country VALUES ("Yemen", 887, "YE", 2, NULL);
INSERT INTO country VALUES ("Zambia", 894, "ZM", 4, NULL);
INSERT INTO country VALUES ("Zimbabwe", 716, "ZW", 4, NULL);


UPDATE country SET population = 35530081 WHERE name = "Afghanistan";
UPDATE country SET population = 2930187 WHERE name = "Albania";
UPDATE country SET population = 41318142 WHERE name = "Algeria";
UPDATE country SET population = 55641 WHERE name = "American Samoa";
UPDATE country SET population = 76965 WHERE name = "Andorra";
UPDATE country SET population = 29784193 WHERE name = "Angola";
UPDATE country SET population = 14909 WHERE name = "Anguilla";
UPDATE country SET population = 102012 WHERE name = "Antigua and Barbuda";
UPDATE country SET population = 44271041 WHERE name = "Argentina";
UPDATE country SET population = 2930450 WHERE name = "Armenia";
UPDATE country SET population = 105264 WHERE name = "Aruba";
UPDATE country SET population = 24450561 WHERE name = "Australia";
UPDATE country SET population = 8735453 WHERE name = "Austria";
UPDATE country SET population = 9827589 WHERE name = "Azerbaijan";
UPDATE country SET population = 395361 WHERE name = "Bahamas";
UPDATE country SET population = 1492584 WHERE name = "Bahrain";
UPDATE country SET population = 164669751 WHERE name = "Bangladesh";
UPDATE country SET population = 285719 WHERE name = "Barbados";
UPDATE country SET population = 9468338 WHERE name = "Belarus";
UPDATE country SET population = 11429336 WHERE name = "Belgium";
UPDATE country SET population = 374681 WHERE name = "Belize";
UPDATE country SET population = 11175692 WHERE name = "Benin";
UPDATE country SET population = 61349 WHERE name = "Bermuda";
UPDATE country SET population = 807610 WHERE name = "Bhutan";
UPDATE country SET population = 11051600 WHERE name = "Bolivia";
UPDATE country SET population = 3507017 WHERE name = "Bosnia and Herzegovina";
UPDATE country SET population = 2291661 WHERE name = "Botswana";
UPDATE country SET population = 209288278 WHERE name = "Brazil";
UPDATE country SET population = 428697 WHERE name = "Brunei";
UPDATE country SET population = 7084571 WHERE name = "Bulgaria";
UPDATE country SET population = 19193382 WHERE name = "Burkina Faso";
UPDATE country SET population = 10864245 WHERE name = "Burundi";
UPDATE country SET population = 16005373 WHERE name = "Cambodia";
UPDATE country SET population = 24053727 WHERE name = "Cameroon";
UPDATE country SET population = 36624199 WHERE name = "Canada";
UPDATE country SET population = 546388 WHERE name = "Cabo Verde";
UPDATE country SET population = 61559 WHERE name = "Cayman Islands";
UPDATE country SET population = 4659080 WHERE name = "Central African Republic";
UPDATE country SET population = 14899994 WHERE name = "Chad";
UPDATE country SET population = 18054726 WHERE name = "Chile";
UPDATE country SET population = 1409517397 WHERE name = "China";
UPDATE country SET population = 2500 WHERE name = "Christmas Island";
UPDATE country SET population = 600 WHERE name = "Cocos (Keeling) Islands";
UPDATE country SET population = 49065615 WHERE name = "Colombia";
UPDATE country SET population = 813912 WHERE name = "Comoros";
UPDATE country SET population = 5260750 WHERE name = "Congo (Brazzaville)";
UPDATE country SET population = 5260750 WHERE name = "Congo (Kinshasa)";
UPDATE country SET population = 17380 WHERE name = "Cook Islands";
UPDATE country SET population = 4905769 WHERE name = "Costa Rica";
UPDATE country SET population = 4189353 WHERE name = "Croatia";
UPDATE country SET population = 11484636 WHERE name = "Cuba";
UPDATE country SET population = 1179551 WHERE name = "Cyprus";
UPDATE country SET population = 10618303 WHERE name = "Czechia";
UPDATE country SET population = 5733551 WHERE name = "Denmark";
UPDATE country SET population = 956985 WHERE name = "Djibouti";
UPDATE country SET population = 73925 WHERE name = "Dominica";
UPDATE country SET population = 10766998 WHERE name = "Dominican Republic";
UPDATE country SET population = 1296311 WHERE name = "Timor-Leste";
UPDATE country SET population = 16624858 WHERE name = "Ecuador";
UPDATE country SET population = 97553151 WHERE name = "Egypt";
UPDATE country SET population = 6377853 WHERE name = "El Salvador";
UPDATE country SET population = 1267689 WHERE name = "Equatorial Guinea";
UPDATE country SET population = 5068831 WHERE name = "Eritrea";
UPDATE country SET population = 1309632 WHERE name = "Estonia";
UPDATE country SET population = 104957438 WHERE name = "Ethiopia";
UPDATE country SET population = 2910 WHERE name = "Falkland Islands (Malvinas)";
UPDATE country SET population = 49290 WHERE name = "Faroe Islands";
UPDATE country SET population = 905502 WHERE name = "Fiji";
UPDATE country SET population = 5523231 WHERE name = "Finland";
UPDATE country SET population = 64979548 WHERE name = "France";
UPDATE country SET population = 282731 WHERE name = "French Guiana";
UPDATE country SET population = 283007 WHERE name = "French Polynesia";
UPDATE country SET population = 2025137 WHERE name = "Gabon";
UPDATE country SET population = 2100568 WHERE name = "Gambia";
UPDATE country SET population = 3912061 WHERE name = "Georgia";
UPDATE country SET population = 82114224 WHERE name = "Germany";
UPDATE country SET population = 28833629 WHERE name = "Ghana";
UPDATE country SET population = 34571 WHERE name = "Gibraltar";
UPDATE country SET population = 11159773 WHERE name = "Greece";
UPDATE country SET population = 56480 WHERE name = "Greenland";
UPDATE country SET population = 107825 WHERE name = "Grenada";
UPDATE country SET population = 449568 WHERE name = "Guadeloupe";
UPDATE country SET population = 164229 WHERE name = "Guam";
UPDATE country SET population = 16913503 WHERE name = "Guatemala";
UPDATE country SET population = 12717176 WHERE name = "Guinea";
UPDATE country SET population = 1861283 WHERE name = "Guinea-Bissau";
UPDATE country SET population = 777859 WHERE name = "Guyana";
UPDATE country SET population = 10981229 WHERE name = "Haiti";
UPDATE country SET population = 1000 WHERE name = "Holy See";
UPDATE country SET population = 9265067 WHERE name = "Honduras";
UPDATE country SET population = 7364883 WHERE name = "Hong Kong";
UPDATE country SET population = 9721559 WHERE name = "Hungary";
UPDATE country SET population = 335025 WHERE name = "Iceland";
UPDATE country SET population = 1339180127 WHERE name = "India";
UPDATE country SET population = 263991379 WHERE name = "Indonesia";
UPDATE country SET population = 81162788 WHERE name = "Iran";
UPDATE country SET population = 38274618 WHERE name = "Iraq";
UPDATE country SET population = 4761657 WHERE name = "Ireland";
UPDATE country SET population = 8321570 WHERE name = "Israel";
UPDATE country SET population = 59359900 WHERE name = "Italy";
UPDATE country SET population = 24294750 WHERE name = "Ivory Coast";
UPDATE country SET population = 2890299 WHERE name = "Jamaica";
UPDATE country SET population = 127484450 WHERE name = "Japan";
UPDATE country SET population = 9702353 WHERE name = "Jordan";
UPDATE country SET population = 18204499 WHERE name = "Kazakhstan";
UPDATE country SET population = 49699862 WHERE name = "Kenya";
UPDATE country SET population = 116398 WHERE name = "Kiribati";
UPDATE country SET population = 4136528 WHERE name = "Kuwait";
UPDATE country SET population = 6045117 WHERE name = "Kyrgyzstan";
UPDATE country SET population = 6858160 WHERE name = "Laos";
UPDATE country SET population = 1949670 WHERE name = "Latvia";
UPDATE country SET population = 6082357 WHERE name = "Lebanon";
UPDATE country SET population = 2233339 WHERE name = "Lesotho";
UPDATE country SET population = 4731906 WHERE name = "Liberia";
UPDATE country SET population = 5605000 WHERE name = "Libya";
UPDATE country SET population = 37922 WHERE name = "Liechtenstein";
UPDATE country SET population = 2890297 WHERE name = "Lithuania";
UPDATE country SET population = 583455 WHERE name = "Luxembourg";
UPDATE country SET population = 473000 WHERE name = "Macao";
UPDATE country SET population = 2024000 WHERE name = "North Macedonia";
UPDATE country SET population = 25570895 WHERE name = "Madagascar";
UPDATE country SET population = 18622104 WHERE name = "Malawi";
UPDATE country SET population = 31624264 WHERE name = "Malaysia";
UPDATE country SET population = 436330 WHERE name = "Maldives";
UPDATE country SET population = 18541980 WHERE name = "Mali";
UPDATE country SET population = 430835 WHERE name = "Malta";
UPDATE country SET population = 53127 WHERE name = "Marshall Islands";
UPDATE country SET population = 384896 WHERE name = "Martinique";
UPDATE country SET population = 4420184 WHERE name = "Mauritania";
UPDATE country SET population = 1265138 WHERE name = "Mauritius";
UPDATE country SET population = 253045 WHERE name = "Mayotte";
UPDATE country SET population = 129163276 WHERE name = "Mexico";
UPDATE country SET population = 4051212 WHERE name = "Moldova";
UPDATE country SET population = 38695 WHERE name = "Monaco";
UPDATE country SET population = 3075647 WHERE name = "Mongolia";
UPDATE country SET population = 631219 WHERE name = "Montenegro";
UPDATE country SET population = 5177 WHERE name = "Montserrat";
UPDATE country SET population = 35739580 WHERE name = "Morocco";
UPDATE country SET population = 29668834 WHERE name = "Mozambique";
UPDATE country SET population = 53370609 WHERE name = "Myanmar";
UPDATE country SET population = 2533794 WHERE name = "Namibia";
UPDATE country SET population = 11359 WHERE name = "Nauru";
UPDATE country SET population = 29304998 WHERE name = "Nepal";
UPDATE country SET population = 17035938 WHERE name = "Netherlands";
UPDATE country SET population = 217000 WHERE name = "Netherlands Antilles";
UPDATE country SET population = 276255 WHERE name = "New Caledonia";
UPDATE country SET population = 4705818 WHERE name = "New Zealand";
UPDATE country SET population = 6217581 WHERE name = "Nicaragua";
UPDATE country SET population = 21477348 WHERE name = "Niger";
UPDATE country SET population = 190886311 WHERE name = "Nigeria";
UPDATE country SET population = 1618 WHERE name = "Niue";
UPDATE country SET population = 2000 WHERE name = "Norfolk Island";
UPDATE country SET population = 25490965 WHERE name = "Korea, Republic of";
UPDATE country SET population = 55144 WHERE name = "Northern Mariana Islands";
UPDATE country SET population = 5305383 WHERE name = "Norway";
UPDATE country SET population = 4636262 WHERE name = "Oman";
UPDATE country SET population = 197015955 WHERE name = "Pakistan";
UPDATE country SET population = 21729 WHERE name = "Palau";
UPDATE country SET population = 4920724 WHERE name = "Palestine, State of";
UPDATE country SET population = 4098587 WHERE name = "Panama";
UPDATE country SET population = 8251162 WHERE name = "Papua New Guinea";
UPDATE country SET population = 6811297 WHERE name = "Paraguay";
UPDATE country SET population = 32165485 WHERE name = "Peru";
UPDATE country SET population = 104918090 WHERE name = "Philippines";
UPDATE country SET population = 50 WHERE name = "Pitcairn";
UPDATE country SET population = 38170712 WHERE name = "Poland";
UPDATE country SET population = 10329506 WHERE name = "Portugal";
UPDATE country SET population = 3663131 WHERE name = "Puerto Rico";
UPDATE country SET population = 2639211 WHERE name = "Qatar";
UPDATE country SET population = 699000 WHERE name = "RÃ©union";
UPDATE country SET population = 19679306 WHERE name = "Romania";
UPDATE country SET population = 143989754 WHERE name = "Russia";
UPDATE country SET population = 12208407 WHERE name = "Rwanda";
UPDATE country SET population = 4049 WHERE name = "Saint Helena, Ascension and Tristan da Cunha";
UPDATE country SET population = 55345 WHERE name = "Saint Kitts and Nevis";
UPDATE country SET population = 178844 WHERE name = "Saint Lucia";
UPDATE country SET population = 6320 WHERE name = "Saint Pierre and Miquelon";
UPDATE country SET population = 109897 WHERE name = "Saint Vincent and the Grenadines";
UPDATE country SET population = 196440 WHERE name = "Samoa";
UPDATE country SET population = 33400 WHERE name = "San Marino";
UPDATE country SET population = 204327 WHERE name = "Sao Tome and Principe";
UPDATE country SET population = 32938213 WHERE name = "Saudi Arabia";
UPDATE country SET population = 15850567 WHERE name = "Senegal";
UPDATE country SET population = 94737 WHERE name = "Seychelles";
UPDATE country SET population = 7557212 WHERE name = "Sierra Leone";
UPDATE country SET population = 5708844 WHERE name = "Singapore";
UPDATE country SET population = 5447662 WHERE name = "Slovakia";
UPDATE country SET population = 2079976 WHERE name = "Slovenia";
UPDATE country SET population = 611343 WHERE name = "Solomon Islands";
UPDATE country SET population = 14742523 WHERE name = "Somalia";
UPDATE country SET population = 56717156 WHERE name = "South Africa";
UPDATE country SET population = 50982212 WHERE name = "Korea, South";
UPDATE country SET population = 12575714 WHERE name = "South Sudan";
UPDATE country SET population = 46354321 WHERE name = "Spain";
UPDATE country SET population = 20876917 WHERE name = "Sri Lanka";
UPDATE country SET population = 40533330 WHERE name = "Sudan";
UPDATE country SET population = 563402 WHERE name = "Suriname";
UPDATE country SET population = 3200 WHERE name = "Svalbard and Jan Mayen";
UPDATE country SET population = 1008000 WHERE name = "Swaziland";
UPDATE country SET population = 9910701 WHERE name = "Sweden";
UPDATE country SET population = 8476005 WHERE name = "Switzerland";
UPDATE country SET population = 18269868 WHERE name = "Syria";
UPDATE country SET population = 8921343 WHERE name = "Tajikistan";
UPDATE country SET population = 57310019 WHERE name = "Tanzania";
UPDATE country SET population = 69037513 WHERE name = "Thailand";
UPDATE country SET population = 7797694 WHERE name = "Togo";
UPDATE country SET population = 1300 WHERE name = "Tokelau";
UPDATE country SET population = 108020 WHERE name = "Tonga";
UPDATE country SET population = 1369125 WHERE name = "Trinidad and Tobago";
UPDATE country SET population = 11532127 WHERE name = "Tunisia";
UPDATE country SET population = 80745020 WHERE name = "Turkey";
UPDATE country SET population = 5758075 WHERE name = "Turkmenistan";
UPDATE country SET population = 35446 WHERE name = "Turks and Caicos Islands";
UPDATE country SET population = 11192 WHERE name = "Tuvalu";
UPDATE country SET population = 42862958 WHERE name = "Uganda";
UPDATE country SET population = 44222947 WHERE name = "Ukraine";
UPDATE country SET population = 9400145 WHERE name = "United Arab Emirates";
UPDATE country SET population = 66181585 WHERE name = "United Kingdom";
UPDATE country SET population = 324459463 WHERE name = "US";
UPDATE country SET population = 3456750 WHERE name = "Uruguay";
UPDATE country SET population = 31910641 WHERE name = "Uzbekistan";
UPDATE country SET population = 276244 WHERE name = "Vanuatu";
UPDATE country SET population = 31977065 WHERE name = "Venezuela";
UPDATE country SET population = 95540800 WHERE name = "Vietnam";
UPDATE country SET population = 11773 WHERE name = "Wallis and Futuna";
UPDATE country SET population = 552628 WHERE name = "Western Sahara";
UPDATE country SET population = 28250420 WHERE name = "Yemen";
UPDATE country SET population = 10640000 WHERE name = "Yugoslavia";
UPDATE country SET population = 17094130 WHERE name = "Zambia";
UPDATE country SET population = 16529904 WHERE name = "Zimbabwe";
UPDATE country SET population = 7100245 WHERE name = "Serbia";
UPDATE country SET population = 3433 WHERE name = "Antarctica";
UPDATE country SET population = 25987 WHERE name = "Bonaire, Sint Eustatius and Saba";
UPDATE country SET population = 0 WHERE name = "Bouvet Island";
UPDATE country SET population = 4000 WHERE name = "British Indian Ocean Territory";
UPDATE country SET population = 25070000 WHERE name = "Cote d'Ivoire";
UPDATE country SET population = 159849 WHERE name = "Curaçao";
UPDATE country SET population = 1136000 WHERE name = "Eswatini";
UPDATE country SET population = 310 WHERE name = "French Southern Territories";
UPDATE country SET population = 66697 WHERE name = "Guernsey";
UPDATE country SET population = 0 WHERE name = "Heard Island and McDonald Islands";
UPDATE country SET population = 84077 WHERE name = "Isle of Man";
UPDATE country SET population = 97857 WHERE name = "Jersey";
UPDATE country SET population = 112640 WHERE name = "Micronesia (Federated States of)";
UPDATE country SET population = 53710000 WHERE name = "Burma";
UPDATE country SET population = 859959 WHERE name = "Réunion";
UPDATE country SET population = 9131 WHERE name = "Saint Barthélemy";
UPDATE country SET population = 40654 WHERE name = "Sint Maarten (Dutch part)";
UPDATE country SET population = 30 WHERE name = "South Georgia and the South Sandwich Islands";
UPDATE country SET population = 23780000 WHERE name = "Taiwan*";
UPDATE country SET population = 300 WHERE name = "United States Minor Outlying Islands";
UPDATE country SET population = 29802 WHERE name = "Virgin Islands (British)";
UPDATE country SET population = 106977 WHERE name = "Virgin Islands (U.S.)";
UPDATE country SET population = 37264 WHERE name = "Saint Martin (French part)";
UPDATE country SET population = 28007 WHERE name = "Åland Islands";
UPDATE country SET population = 1124 WHERE population is NULL;
