DELETE FROM country;
DELETE FROM region;

INSERT INTO region VALUES (1, "Europe");
INSERT INTO region VALUES (2, "Asia");
INSERT INTO region VALUES (3, "Americas");
INSERT INTO region VALUES (4, "Africa");
INSERT INTO region VALUES (5, "Oceania");
INSERT INTO region VALUES (6, "Other");

INSERT INTO country VALUES ("Afghanistan", 004, "AF", 2);
INSERT INTO country VALUES ("Åland Islands", 248, "AX", 1);
INSERT INTO country VALUES ("Albania", 008, "AL", 1);
INSERT INTO country VALUES ("Algeria", 012, "DZ", 4);
INSERT INTO country VALUES ("American Samoa", 016, "AS", 5);
INSERT INTO country VALUES ("Andorra", 020, "AD", 1);
INSERT INTO country VALUES ("Angola", 024, "AO", 4);
INSERT INTO country VALUES ("Anguilla", 660, "AI", 3);
INSERT INTO country VALUES ("Antarctica", 010, "AQ", 6);
INSERT INTO country VALUES ("Antigua and Barbuda", 028, "AG", 3);
INSERT INTO country VALUES ("Argentina", 032, "AR", 3);
INSERT INTO country VALUES ("Armenia", 051, "AM", 2);
INSERT INTO country VALUES ("Aruba", 533, "AW", 3);
INSERT INTO country VALUES ("Australia", 036, "AU", 5);
INSERT INTO country VALUES ("Austria", 040, "AT", 1);
INSERT INTO country VALUES ("Azerbaijan", 031, "AZ", 2);
INSERT INTO country VALUES ("Bahamas", 044, "BS", 3);
INSERT INTO country VALUES ("Bahrain", 048, "BH", 2);
INSERT INTO country VALUES ("Bangladesh", 050, "BD", 2);
INSERT INTO country VALUES ("Barbados", 052, "BB", 3);
INSERT INTO country VALUES ("Belarus", 112, "BY", 1);
INSERT INTO country VALUES ("Belgium", 056, "BE", 1);
INSERT INTO country VALUES ("Belize", 084, "BZ", 3);
INSERT INTO country VALUES ("Benin", 204, "BJ", 4);
INSERT INTO country VALUES ("Bermuda", 060, "BM", 3);
INSERT INTO country VALUES ("Bhutan", 064, "BT", 2);
INSERT INTO country VALUES ("Bolivia", 068, "BO", 3);
INSERT INTO country VALUES ("Bonaire, Sint Eustatius and Saba", 535, "BQ", 3);
INSERT INTO country VALUES ("Bosnia and Herzegovina", 070, "BA", 1);
INSERT INTO country VALUES ("Botswana", 072, "BW", 4);
INSERT INTO country VALUES ("Bouvet Island", 074, "BV", 3);
INSERT INTO country VALUES ("Brazil", 076, "BR", 3);
INSERT INTO country VALUES ("British Indian Ocean Territory", 086, "IO", 4);
INSERT INTO country VALUES ("Brunei", 096, "BN", 2);
INSERT INTO country VALUES ("Bulgaria", 100, "BG", 1);
INSERT INTO country VALUES ("Burkina Faso", 854, "BF", 4);
INSERT INTO country VALUES ("Burundi", 108, "BI", 4);
INSERT INTO country VALUES ("Cabo Verde", 132, "CV", 4);
INSERT INTO country VALUES ("Cambodia", 116, "KH", 2);
INSERT INTO country VALUES ("Cameroon", 120, "CM", 4);
INSERT INTO country VALUES ("Canada", 124, "CA", 3);
INSERT INTO country VALUES ("Cayman Islands", 136, "KY", 3);
INSERT INTO country VALUES ("Central African Republic", 140, "CF", 4);
INSERT INTO country VALUES ("Chad", 148, "TD", 4);
INSERT INTO country VALUES ("Chile", 152, "CL", 3);
INSERT INTO country VALUES ("China", 156, "CN", 2);
INSERT INTO country VALUES ("Christmas Island", 162, "CX", 5);
INSERT INTO country VALUES ("Cocos (Keeling) Islands", 166, "CC", 5);
INSERT INTO country VALUES ("Colombia", 170, "CO", 3);
INSERT INTO country VALUES ("Comoros", 174, "KM", 4);
INSERT INTO country VALUES ("Congo (Brazzaville)", 178, "CG", 4);
INSERT INTO country VALUES ("Congo (Kinshasa)", 180, "CD", 4);
INSERT INTO country VALUES ("Cook Islands", 184, "CK", 5);
INSERT INTO country VALUES ("Costa Rica", 188, "CR", 3);
INSERT INTO country VALUES ("Cote d'Ivoire", 384, "CI", 4);
INSERT INTO country VALUES ("Croatia", 191, "HR", 1);
INSERT INTO country VALUES ("Cuba", 192, "CU", 3);
INSERT INTO country VALUES ("Curaçao", 531, "CW", 3);
INSERT INTO country VALUES ("Cyprus", 196, "CY", 2);
INSERT INTO country VALUES ("Czechia", 203, "CZ", 1);
INSERT INTO country VALUES ("Denmark", 208, "DK", 1);
INSERT INTO country VALUES ("Djibouti", 262, "DJ", 4);
INSERT INTO country VALUES ("Dominica", 212, "DM", 3);
INSERT INTO country VALUES ("Dominican Republic", 214, "DO", 3);
INSERT INTO country VALUES ("Ecuador", 218, "EC", 3);
INSERT INTO country VALUES ("Egypt", 818, "EG", 4);
INSERT INTO country VALUES ("El Salvador", 222, "SV", 3);
INSERT INTO country VALUES ("Equatorial Guinea", 226, "GQ", 4);
INSERT INTO country VALUES ("Eritrea", 232, "ER", 4);
INSERT INTO country VALUES ("Estonia", 233, "EE", 1);
INSERT INTO country VALUES ("Eswatini", 748, "SZ", 4);
INSERT INTO country VALUES ("Ethiopia", 231, "ET", 4);
INSERT INTO country VALUES ("Falkland Islands (Malvinas)", 238, "FK", 3);
INSERT INTO country VALUES ("Faroe Islands", 234, "FO", 1);
INSERT INTO country VALUES ("Fiji", 242, "FJ", 5);
INSERT INTO country VALUES ("Finland", 246, "FI", 1);
INSERT INTO country VALUES ("France", 250, "FR", 1);
INSERT INTO country VALUES ("French Guiana", 254, "GF", 3);
INSERT INTO country VALUES ("French Polynesia", 258, "PF", 5);
INSERT INTO country VALUES ("French Southern Territories", 260, "TF", 4);
INSERT INTO country VALUES ("Gabon", 266, "GA", 4);
INSERT INTO country VALUES ("Gambia", 270, "GM", 4);
INSERT INTO country VALUES ("Georgia", 268, "GE", 2);
INSERT INTO country VALUES ("Germany", 276, "DE", 1);
INSERT INTO country VALUES ("Ghana", 288, "GH", 4);
INSERT INTO country VALUES ("Gibraltar", 292, "GI", 1);
INSERT INTO country VALUES ("Greece", 300, "GR", 1);
INSERT INTO country VALUES ("Greenland", 304, "GL", 3);
INSERT INTO country VALUES ("Grenada", 308, "GD", 3);
INSERT INTO country VALUES ("Guadeloupe", 312, "GP", 3);
INSERT INTO country VALUES ("Guam", 316, "GU", 5);
INSERT INTO country VALUES ("Guatemala", 320, "GT", 3);
INSERT INTO country VALUES ("Guernsey", 831, "GG", 1);
INSERT INTO country VALUES ("Guinea", 324, "GN", 4);
INSERT INTO country VALUES ("Guinea-Bissau", 624, "GW", 4);
INSERT INTO country VALUES ("Guyana", 328, "GY", 3);
INSERT INTO country VALUES ("Haiti", 332, "HT", 3);
INSERT INTO country VALUES ("Heard Island and McDonald Islands", 334, "HM", 5);
INSERT INTO country VALUES ("Holy See", 336, "VA", 1);
INSERT INTO country VALUES ("Honduras", 340, "HN", 3);
INSERT INTO country VALUES ("Hong Kong", 344, "HK", 2);
INSERT INTO country VALUES ("Hungary", 348, "HU", 1);
INSERT INTO country VALUES ("Iceland", 352, "IS", 1);
INSERT INTO country VALUES ("India", 356, "IN", 2);
INSERT INTO country VALUES ("Indonesia", 360, "ID", 2);
INSERT INTO country VALUES ("Iran", 364, "IR", 2);
INSERT INTO country VALUES ("Iraq", 368, "IQ", 2);
INSERT INTO country VALUES ("Ireland", 372, "IE", 1);
INSERT INTO country VALUES ("Isle of Man", 833, "IM", 1);
INSERT INTO country VALUES ("Israel", 376, "IL", 2);
INSERT INTO country VALUES ("Italy", 380, "IT", 1);
INSERT INTO country VALUES ("Jamaica", 388, "JM", 3);
INSERT INTO country VALUES ("Japan", 392, "JP", 2);
INSERT INTO country VALUES ("Jersey", 832, "JE", 1);
INSERT INTO country VALUES ("Jordan", 400, "JO", 2);
INSERT INTO country VALUES ("Kazakhstan", 398, "KZ", 2);
INSERT INTO country VALUES ("Kenya", 404, "KE", 4);
INSERT INTO country VALUES ("Kiribati", 296, "KI", 5);
INSERT INTO country VALUES ("Korea, South", 408, "KP", 2);
INSERT INTO country VALUES ("Korea, Republic of", 410, "KR", 2);
INSERT INTO country VALUES ("Kuwait", 414, "KW", 2);
INSERT INTO country VALUES ("Kyrgyzstan", 417, "KG", 2);
INSERT INTO country VALUES ("Laos", 418, "LA", 2);
INSERT INTO country VALUES ("Latvia", 428, "LV", 1);
INSERT INTO country VALUES ("Lebanon", 422, "LB", 2);
INSERT INTO country VALUES ("Lesotho", 426, "LS", 4);
INSERT INTO country VALUES ("Liberia", 430, "LR", 4);
INSERT INTO country VALUES ("Libya", 434, "LY", 4);
INSERT INTO country VALUES ("Liechtenstein", 438, "LI", 1);
INSERT INTO country VALUES ("Lithuania", 440, "LT", 1);
INSERT INTO country VALUES ("Luxembourg", 442, "LU", 1);
INSERT INTO country VALUES ("Macao", 446, "MO", 2);
INSERT INTO country VALUES ("Madagascar", 450, "MG", 4);
INSERT INTO country VALUES ("Malawi", 454, "MW", 4);
INSERT INTO country VALUES ("Malaysia", 458, "MY", 2);
INSERT INTO country VALUES ("Maldives", 462, "MV", 2);
INSERT INTO country VALUES ("Mali", 466, "ML", 4);
INSERT INTO country VALUES ("Malta", 470, "MT", 1);
INSERT INTO country VALUES ("Marshall Islands", 584, "MH", 5);
INSERT INTO country VALUES ("Martinique", 474, "MQ", 3);
INSERT INTO country VALUES ("Mauritania", 478, "MR", 4);
INSERT INTO country VALUES ("Mauritius", 480, "MU", 4);
INSERT INTO country VALUES ("Mayotte", 175, "YT", 4);
INSERT INTO country VALUES ("Mexico", 484, "MX", 3);
INSERT INTO country VALUES ("Micronesia (Federated States of)", 583, "FM", 5);
INSERT INTO country VALUES ("Moldova", 498, "MD", 1);
INSERT INTO country VALUES ("Monaco", 492, "MC", 1);
INSERT INTO country VALUES ("Mongolia", 496, "MN", 2);
INSERT INTO country VALUES ("Montenegro", 499, "ME", 1);
INSERT INTO country VALUES ("Montserrat", 500, "MS", 3);
INSERT INTO country VALUES ("Morocco", 504, "MA", 4);
INSERT INTO country VALUES ("Mozambique", 508, "MZ", 4);
INSERT INTO country VALUES ("Burma", 104, "MM", 2);
INSERT INTO country VALUES ("Namibia", 516, "NA", 4);
INSERT INTO country VALUES ("Nauru", 520, "NR", 5);
INSERT INTO country VALUES ("Nepal", 524, "NP", 2);
INSERT INTO country VALUES ("Netherlands", 528, "NL", 1);
INSERT INTO country VALUES ("New Caledonia", 540, "NC", 5);
INSERT INTO country VALUES ("New Zealand", 554, "NZ", 5);
INSERT INTO country VALUES ("Nicaragua", 558, "NI", 3);
INSERT INTO country VALUES ("Niger", 562, "NE", 4);
INSERT INTO country VALUES ("Nigeria", 566, "NG", 4);
INSERT INTO country VALUES ("Niue", 570, "NU", 5);
INSERT INTO country VALUES ("Norfolk Island", 574, "NF", 5);
INSERT INTO country VALUES ("North Macedonia", 807, "MK", 1);
INSERT INTO country VALUES ("Northern Mariana Islands", 580, "MP", 5);
INSERT INTO country VALUES ("Norway", 578, "NO", 1);
INSERT INTO country VALUES ("Oman", 512, "OM", 2);
INSERT INTO country VALUES ("Pakistan", 586, "PK", 2);
INSERT INTO country VALUES ("Palau", 585, "PW", 5);
INSERT INTO country VALUES ("Palestine, State of", 275, "PS", 2);
INSERT INTO country VALUES ("Panama", 591, "PA", 3);
INSERT INTO country VALUES ("Papua New Guinea", 598, "PG", 5);
INSERT INTO country VALUES ("Paraguay", 600, "PY", 3);
INSERT INTO country VALUES ("Peru", 604, "PE", 3);
INSERT INTO country VALUES ("Philippines", 608, "PH", 2);
INSERT INTO country VALUES ("Pitcairn", 612, "PN", 5);
INSERT INTO country VALUES ("Poland", 616, "PL", 1);
INSERT INTO country VALUES ("Portugal", 620, "PT", 1);
INSERT INTO country VALUES ("Puerto Rico", 630, "PR", 3);
INSERT INTO country VALUES ("Qatar", 634, "QA", 2);
INSERT INTO country VALUES ("Réunion", 638, "RE", 4);
INSERT INTO country VALUES ("Romania", 642, "RO", 1);
INSERT INTO country VALUES ("Russia", 643, "RU", 1);
INSERT INTO country VALUES ("Rwanda", 646, "RW", 4);
INSERT INTO country VALUES ("Saint Barthélemy", 652, "BL", 3);
INSERT INTO country VALUES ("Saint Helena, Ascension and Tristan da Cunha", 654, "SH", 4);
INSERT INTO country VALUES ("Saint Kitts and Nevis", 659, "KN", 3);
INSERT INTO country VALUES ("Saint Lucia", 662, "LC", 3);
INSERT INTO country VALUES ("Saint Martin (French part)", 663, "MF", 3);
INSERT INTO country VALUES ("Saint Pierre and Miquelon", 666, "PM", 3);
INSERT INTO country VALUES ("Saint Vincent and the Grenadines", 670, "VC", 3);
INSERT INTO country VALUES ("Samoa", 882, "WS", 5);
INSERT INTO country VALUES ("San Marino", 674, "SM", 1);
INSERT INTO country VALUES ("Sao Tome and Principe", 678, "ST", 4);
INSERT INTO country VALUES ("Saudi Arabia", 682, "SA", 2);
INSERT INTO country VALUES ("Senegal", 686, "SN", 4);
INSERT INTO country VALUES ("Serbia", 688, "RS", 1);
INSERT INTO country VALUES ("Seychelles", 690, "SC", 4);
INSERT INTO country VALUES ("Sierra Leone", 694, "SL", 4);
INSERT INTO country VALUES ("Singapore", 702, "SG", 2);
INSERT INTO country VALUES ("Sint Maarten (Dutch part)", 534, "SX", 3);
INSERT INTO country VALUES ("Slovakia", 703, "SK", 1);
INSERT INTO country VALUES ("Slovenia", 705, "SI", 1);
INSERT INTO country VALUES ("Solomon Islands", 090, "SB", 5);
INSERT INTO country VALUES ("Somalia", 706, "SO", 4);
INSERT INTO country VALUES ("South Africa", 710, "ZA", 4);
INSERT INTO country VALUES ("South Georgia and the South Sandwich Islands", 239, "GS", 3);
INSERT INTO country VALUES ("South Sudan", 728, "SS", 4);
INSERT INTO country VALUES ("Spain", 724, "ES", 1);
INSERT INTO country VALUES ("Sri Lanka", 144, "LK", 2);
INSERT INTO country VALUES ("Sudan", 729, "SD", 4);
INSERT INTO country VALUES ("Suriname", 740, "SR", 3);
INSERT INTO country VALUES ("Svalbard and Jan Mayen", 744, "SJ", 1);
INSERT INTO country VALUES ("Sweden", 752, "SE", 1);
INSERT INTO country VALUES ("Switzerland", 756, "CH", 1);
INSERT INTO country VALUES ("Syria", 760, "SY", 2);
INSERT INTO country VALUES ("Taiwan*", 158, "TW", 2);
INSERT INTO country VALUES ("Tajikistan", 762, "TJ", 2);
INSERT INTO country VALUES ("Tanzania", 834, "TZ", 4);
INSERT INTO country VALUES ("Thailand", 764, "TH", 2);
INSERT INTO country VALUES ("Timor-Leste", 626, "TL", 2);
INSERT INTO country VALUES ("Togo", 768, "TG", 4);
INSERT INTO country VALUES ("Tokelau", 772, "TK", 5);
INSERT INTO country VALUES ("Tonga", 776, "TO", 5);
INSERT INTO country VALUES ("Trinidad and Tobago", 780, "TT", 3);
INSERT INTO country VALUES ("Tunisia", 788, "TN", 4);
INSERT INTO country VALUES ("Turkey", 792, "TR", 2);
INSERT INTO country VALUES ("Turkmenistan", 795, "TM", 2);
INSERT INTO country VALUES ("Turks and Caicos Islands", 796, "TC", 3);
INSERT INTO country VALUES ("Tuvalu", 798, "TV", 5);
INSERT INTO country VALUES ("Uganda", 800, "UG", 4);
INSERT INTO country VALUES ("Ukraine", 804, "UA", 1);
INSERT INTO country VALUES ("United Arab Emirates", 784, "AE", 2);
INSERT INTO country VALUES ("United Kingdom", 826, "GB", 1);
INSERT INTO country VALUES ("US", 840, "US", 3);
INSERT INTO country VALUES ("United States Minor Outlying Islands", 581, "UM", 5);
INSERT INTO country VALUES ("Uruguay", 858, "UY", 3);
INSERT INTO country VALUES ("Uzbekistan", 860, "UZ", 2);
INSERT INTO country VALUES ("Vanuatu", 548, "VU", 5);
INSERT INTO country VALUES ("Venezuela", 862, "VE", 3);
INSERT INTO country VALUES ("Vietnam", 704, "VN", 2);
INSERT INTO country VALUES ("Virgin Islands (British)", 092, "VG", 3);
INSERT INTO country VALUES ("Virgin Islands (U.S.)", 850, "VI", 3);
INSERT INTO country VALUES ("Wallis and Futuna", 876, "WF", 5);
INSERT INTO country VALUES ("Western Sahara", 732, "EH", 4);
INSERT INTO country VALUES ("Yemen", 887, "YE", 2);
INSERT INTO country VALUES ("Zambia", 894, "ZM", 4);
INSERT INTO country VALUES ("Zimbabwe", 716, "ZW", 4);
